version: '3.3'
services:
    web:
        build:
            context: ./php
            dockerfile: Dockerfile
        container_name: web_form_mahasiswa
        depends_on:
            - db
        volumes:
            - ./php:/var/www/html/
        ports:
            - 8000:80
    db:
        build:
            context: ./mariadb
            dockerfile: Dockerfile
        container_name: mysql_form_mahasiswa
        restart: always
        ports:
            - 6033:3306